import nworts.pkgopts
import unittest
import logging
suite "Basic options tests":
    const cmakeopts = """
# This is the CMakeCache file.
# For build in directory: c:/Users/barch/Documents/source/worts/worts/libarchive/build
# It was generated by CMake: C:/Program Files/CMake/bin/cmake.exe
# You can edit this file to change values found and used by cmake.
# If you do not want to change any of the values, simply exit the editor.
# If you do want to change a value, simply edit, save, and exit the editor.
# The syntax for the file is as follows:
# KEY:TYPE=VALUE
# KEY is the name of a variable in the cache.
# TYPE is a hint to GUIs for the type of VALUE, DO NOT EDIT TYPE!.
# VALUE is the current value for the KEY.

########################
# EXTERNAL cache entries
########################

CMAKE_BUILD_TYPE:STRING=Release

//Build the testing tree.
BUILD_TESTING:BOOL=OFF
    """

    test "has CMakeBuildType":
        var opts = cmake_genopts(cmakeopts)
        var idx = opts.find("CMAKE_BUILD_TYPE")
        check(idx != -1)
        var opt = opts[idx]
        check(opt.typ == "STRING")
        check(opt.default == "Release")
        check(opt.value == "Release")
    test "has BuildTesting":
        var opts = cmake_genopts(cmakeopts)
        var idx = opts.find("BUILD_TESTING")
        check(idx != -1)
        var opt = opts[idx]
        check(opt.typ == "BOOL")
        check(opt.default == "OFF")
        check(opt.value == "OFF")

